version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eatinghealthy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14udktfoz9o2h"
s3_prefix = "eatinghealthy"
region = "me-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
